# Generated by Django 5.1.3 on 2024-11-05 10:01

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_gender_alter_customuser_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=user.models.save_user_img),
        ),
    ]
